site_name: Documentation CUB
site_url: https://joris-texier.github.io/documentation-cub/
theme:
  name: material
  language: fr
  palette:
    primary: indigo
    accent: blue

nav:
  - Accueil: index.md
  - CUB:
      - Introduction: CUB/index.md
      - Administration des infrastructures: CUB/AdminInfra/index.md
      - Administration des services: CUB/AdminServ/index.md
      - Administration des systèmes: CUB/AdminSys/index.md
      - Cybersécurité: CUB/Cybersécurité/index.md

markdown_extensions:
  - toc:
      permalink: true
  - tables
  - admonition
  - codehilite
  - footnotes
  - attr_list
