site_name: Le contexte CUB et AP
site_url: https://joris-texier.github.io/documentation-cub/
theme:
  name: material
  language: fr
  features:
    - content.code.copy
  palette:
    primary: indigo
    accent: blue

nav:
  - Accueil: index.md

  - CUB:
      - Contexte:
          - Présentation du contexte CUB: CUB/Contexte/01-presentation.md
          - Schéma réseau de l'entreprise CUB: CUB/Contexte/02-schemas.md
          - Description de l'infrastructure: CUB/Contexte/03-infra.md
          - Référentiel défini par la DSI: CUB/Contexte/bonnespratiques.md

      - Documentation:
          - Administration des infrastructures:
              - Situation0 - AdminInfra - CUB: CUB/Documentation/AdminInfra/Situation0-AdminInfra-CUB.md
          - Administration des services:
              - Situation1 - AdminServ - CUB: CUB/Documentation/AdminServ/Situation1-AdminServ-CUB.md
          - Administration des systèmes:
              - Situation1 - AdminSys - CUB: CUB/Documentation/AdminSys/Situation1-AdminSys-CUB.md
              - Situation2 - AdminSys - CUB: CUB/Documentation/AdminSys/Situation2-AdminSys-CUB.md
              - Situation3 - AdminSys - CUB: CUB/Documentation/AdminSys/Situation3-AdminSys-CUB.md
          - Cybersécurité:
              - Situation1 - Cybersécurité - CUB: CUB/Documentation/Cybersécurité/Situation1-Cyber-CUB.md
              - Situation2 - Cybersécurité - CUB: CUB/Documentation/Cybersécurité/Situation2-Cyber-CUB.md
              - Situation3 - Cybersécurité - CUB: CUB/Documentation/Cybersécurité/Situation3-Cyber-CUB.md
              - Situation4 - Cybersécurité - CUB: CUB/Documentation/Cybersécurité/Situation4-Cyber-CUB.md

  - AP:
      - Contexte:
          - Contexte général EPOKA: AP/Contexte/AP-Contexte.md
          - Contexte SP0: AP/Documentation/SP0/SP0-Contexte.md
          - Contexte SP2: AP/Documentation/SP2/SP2-Contexte.md

      - Documentation:
          - SP0:
              - Mission 1 - Adapter le plan d’adressage: AP/Documentation/SP0/Mission1/SP0_Mission1_Adapter.md
              - Mission 2 - Mise en place d’un serveur AD/DHCP: AP/Documentation/SP0/Mission2/SP0-Mission2-AD_DHCP.md
              - Mission 3 - Mise en place d’un serveur NAS: AP/Documentation/SP0/Mission3/SP0-Mission3-NAS.md
              - Mission 3 - Mise en place d’un serveur GLPI: AP/Documentation/SP0/Mission3/SP0-Mission3-GLPI.md
              - Mission 4 - Documentation de l’architecture réseau: AP/Documentation/SP0/Mission4/SP0-Mission4-Architecture-Reseau.md
          - SP2:
              - Mission 1: AP/Documentation/SP2/Mission1/index.md
              - Mission 2: AP/Documentation/SP2/Mission2/index.md

markdown_extensions:
  - toc:
      permalink: true
  - tables
  - admonition
  - codehilite
  - footnotes
  - attr_list
