site_name: Documentation CUB
site_url: https://joris-texier.github.io/documentation-cub/
theme:
  name: material
  language: fr
  palette:
    primary: indigo
    accent: blue

nav:
  - Accueil: index.md
  - CUB: index.md

markdown_extensions:
  - toc:
      permalink: true
  - tables
  - admonition
  - codehilite
  - footnotes
  - attr_list
