site_name: Documentation CUB
site_url: https://joris-texier.github.io/documentation-cub/
theme:
  name: material
  language: fr
  palette:
    primary: indigo
    accent: blue

nav:
  - Accueil: index.md
  - CUB:
      - Contexte:

      - Documentation:
          - Administration des infrastructures: CUB/Documentation/AdminInfra/index.md
          - Administration des services: CUB/Documentation/AdminServ/index.md
          - Administration des systèmes: CUB/Documentation/AdminSys/index.md
          - Cybersécurité: CUB/Documentation/Cybersécurité/index.md

markdown_extensions:
  - toc:
      permalink: true
  - tables
  - admonition
  - codehilite
  - footnotes
  - attr_list
