site_name: Le contexte CUB
site_url: https://joris-texier.github.io/documentation-cub/
theme:
  name: material
  language: fr
  features:
    - content.code.copy
  palette:
    primary: indigo
    accent: blue

nav:
  - CUB:
      - Contexte:
          - Présentation du contexte CUB: CUB/Contexte/01-presentation.md
          - Schéma réseau de l'entreprise CUB: CUB/Contexte/02-schemas.md
          - Description de l'infrastructure: CUB/Contexte/03-infra.md
          - Référentiel défini par la DSI: CUB/Contexte/bonnespratiques.md
      - Documentation:
          - Administration des infrastructures:
              - Situation0 - AdminInfra - CUB: CUB/Documentation/AdminInfra/Situation0-AdminInfra-CUB.md

          - Administration des services:
              - Situation1 - AdminServ - CUB: CUB/Documentation/AdminServ/Situation1-AdminServ-CUB.md

          - Administration des systèmes:
              - Situation1 - AdminSys - CUB: CUB/Documentation/AdminSys/Situation1-AdminSys-CUB.md
              - Situation2 - AdminSys - CUB: CUB/Documentation/AdminSys/Situation2-AdminSys-CUB.md
              - Situation3 - AdminSys - CUB: CUB/Documentation/AdminSys/Situation3-AdminSys-CUB.md

          - Cybersécurité:
              - Situation1 - Cybersécurité - CUB: CUB/Documentation/Cybersécurité/Situation1-Cyber-CUB.md
              - Situation2 - Cybersécurité - CUB: CUB/Documentation/Cybersécurité/Situation2-Cyber-CUB.md
              - Situation3 - Cybersécurité - CUB: CUB/Documentation/Cybersécurité/Situation3-Cyber-CUB.md
              - Situation4 - Cybersécurité - CUB: CUB/Documentation/Cybersécurité/Situation4-Cyber-CUB.md




markdown_extensions:
  - toc:
      permalink: true
  - tables
  - admonition
  - codehilite
  - footnotes
  - attr_list
