site_name: Le contexte CUB
site_url: https://joris-texier.github.io/documentation-cub/
theme:
  name: material
  language: fr
  palette:
    primary: indigo
    accent: blue

nav:
  - CUB:
      - Contexte:
          - Présentation du contexte CUB: CUB/Contexte/01-presentation.md
          - Schéma réseau de l'entreprise CUB: CUB/Contexte/02-schemas.md
          - Description de l'infrastructure: CUB/Contexte/03-infra.md
          - Référentiel défini par la DSI: CUB/Contexte/bonnespratiques.md
      - Documentation:
          - Administration des infrastructures:
              - Situation0 - AdminInfra - CUB: CUB/Documentation/AdminInfra/Situation0-AdminInfra-CUB.md
          - Administration des services: CUB/Documentation/AdminServ/index.md
              - Situation1 - AdminServ -CUB: CUB/Documentation/AdminServ/Situation1-AdminServ-CUB.md
          - Administration des systèmes: CUB/Documentation/AdminSys/index.md
          - Cybersécurité: CUB/Documentation/Cybersécurité/index.md

markdown_extensions:
  - toc:
      permalink: true
  - tables
  - admonition
  - codehilite
  - footnotes
  - attr_list
