site_name: Le contexte CUB et AP
site_url: https://joris-texier.github.io/documentation-cub/
theme:
  name: material
  logo: media/logo_site.png
  favicon: media/logo_site.png
  language: fr
  features:
    - content.code.copy
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.prune
    - search.suggest
    - search.highlight
    - toc.follow
  palette:
    - scheme: default
      primary: blue gray
      accent: light blue
    - scheme: slate
      primary: blue gray
      accent: light blue
      toggle:
        icon: material/weather-night
        name: Basculer en mode sombre
  font:
    text: Roboto
    code: JetBrains Mono
  footer:
    content: "© 2025 — Documentation réalisée par <b>Joris Texier</b> | <b>JT Design Informatique</b>"

extra_css:
  - assets/stylesheets/custom.css
